### ISSUE TITLE
slice 如何翻译？

### ISSUE THREAD

**Issue by zieckey** [Go-zh/go-zh.github.io#15]
切片？

**Comment by OlingCat** [comment]
嗯，有些术语你可以参考 doc/go_spec.old.html 和https://docs.google.com/spreadsheets/d/1oBEYj0TUCuTDy5vLGsjtMQ_Sd-_FASf393bhC-rfbGQ/edit?usp=sharing

**Comment by zieckey** [comment]
我这边打不开啊。有梯子啊
http://go-zh.github.io/docs/trans-terms.html 这里怎么没有 `slice` 的解释？

**Comment by minux** [comment]
我刚才查了，那个 Google Docs 的 URL 没问题，权限也没问题（任何有 URL 的人都可以评论）。

对，trans-term 里面没列出 slice 的翻译，而且那个 Google Docs 里似乎也没有。。。

**Comment by OlingCat** [comment]
啊..所以说先主要参考源码库里的 doc/go_spec.old.html 文件嘛= =||

**Comment by minux** [comment]
恩 网页版在这里 zh-golang.appspot.com/ref/spec.old

可以在手册里加上这个 URL。

**Comment by OlingCat** [comment]
好

**Comment by minux** [comment]
话说那个 Google Docs 的内容和 trans-terms.md 的内容是一致的吧？

**Comment by OlingCat** [comment]
啊..有些还没更新，等你讨论呢= =||

**Comment by minux** [comment]
哪些要讨论？

**Comment by OlingCat** [comment]
Google Docs 里的

**Comment by minux** [comment]
整理到 #20 了，在那里讨论吧。
