### ISSUE TITLE
句末符号

### ISSUE THREAD

**Issue by Bluek404** [Go-zh/go-zh.github.io#22]
_docs/trans-spec.md 中的第36行句末符号为中文句号

>Abs 返回 x 的绝对值。

而下面则是说

>注释的第一行应为对该包的简单描述，**句末以英文点号“.”结尾**，接着换行以继续详情的翻译。

**Comment by minux** [comment]
恩 只有包文档的第一句必须是英文的句号结尾，这是 godoc 生成包的 SYNOPSIS 的要求。

对于其他类型的文档则没有这个要求，使用中文句号更符合中文的标准。

**Comment by OlingCat** [comment]
这里是指包声明前的注释，参见后面的例子。我会再修改一下翻译规范。
